apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app.kubernetes.io/name: mongo-debugger
    app.kubernetes.io/component: grafana
data:
  datasource.yaml: |
{{ .Files.Get "grafana/datasources/datasource.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  labels:
    app.kubernetes.io/name: mongo-debugger
    app.kubernetes.io/component: grafana
data:
  provider.yaml: |
{{ .Files.Get "grafana/dashboards/provider.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    app.kubernetes.io/name: mongo-debugger
    app.kubernetes.io/component: grafana
data:
  anomaly-focus.json: |
{{ .Files.Get "grafana/dashboards/anomaly-focus.json" | nindent 4 }}
  all-metrics.json: |
{{ .Files.Get "grafana/dashboards/all-metrics.json" | nindent 4 }}
