apiVersion: 1
datasources:
  - name: Mongo Debugger
    uid: mongo-debugger-pg
    type: grafana-simple-json-datasource
    access: proxy
    url: http://api:8000/grafana/simple
    isDefault: true
    editable: false
    jsonData: {}
