apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: mongo-debugger
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: {{ .Values.ui.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.port }}
          env:
            - name: API_UPSTREAM
              value: {{ printf "api:%v" .Values.api.port | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
