{
 "title": "MongoDB FTDC Analytics",
 "tags": [
  "ftdc",
  "all-metrics"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run", "query": "runs" }
  ]
 },
 "panels": [
  { "title": "Assessment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "WiredTiger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "WiredTiger Tickets",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 8, "h": 4 },
   "targets": [
    { "target": "$run_id/ticket_avail_read", "type": "timeserie" },
    { "target": "$run_id/ticket_avail_write", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Cache",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/wt_cache_max", "type": "timeserie" },
    { "target": "$run_id/wt_cache_used", "type": "timeserie" },
    { "target": "$run_id/wt_cache_dirty", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Cache Pages Evicted",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 12, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/wt_modified_evicted", "type": "timeserie" },
    { "target": "$run_id/wt_unmodified_evicted", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Cache I/O",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 12, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/wt_cache_read_in", "type": "timeserie" },
    { "target": "$run_id/wt_cache_written_from", "type": "timeserie" }
   ]
  },
  {
   "title": "WiredTiger Block Manager",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 17, "w": 8, "h": 4 },
   "targets": [
    { "target": "$run_id/wt_blkmgr_read", "type": "timeserie" },
    { "target": "$run_id/wt_blkmgr_written", "type": "timeserie" },
    {
     "target": "$run_id/wt_blkmgr_written_checkpoint",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "WiredTiger Data Handle",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 17, "w": 8, "h": 4 },
   "targets": [
    { "target": "$run_id/wt_dhandles_active", "type": "timeserie" }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 22, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/mem_virtual", "type": "timeserie" },
    { "target": "$run_id/mem_resident", "type": "timeserie" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 22, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/latency_read", "type": "timeserie" },
    { "target": "$run_id/latency_write", "type": "timeserie" },
    { "target": "$run_id/latency_command", "type": "timeserie" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 22, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/conns_current", "type": "timeserie" },
    { "target": "$run_id/conns_created/s", "type": "timeserie" },
    { "target": "$run_id/conns_available", "type": "timeserie" },
    { "target": "$run_id/conns_active", "type": "timeserie" }
   ]
  },
  {
   "title": "Network Requests",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 22, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/net_requests", "type": "timeserie" }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/mem_page_faults", "type": "timeserie" }
   ]
  },
  {
   "title": "Ops Counters",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 27, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/ops_query", "type": "timeserie" },
    { "target": "$run_id/ops_insert", "type": "timeserie" },
    { "target": "$run_id/ops_update", "type": "timeserie" },
    { "target": "$run_id/ops_delete", "type": "timeserie" },
    { "target": "$run_id/ops_getmore", "type": "timeserie" },
    { "target": "$run_id/ops_command", "type": "timeserie" }
   ]
  },
  {
   "title": "Queued Ops",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 27, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/q_queued_read", "type": "timeserie" },
    { "target": "$run_id/q_queued_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Network Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 27, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/net_in", "type": "timeserie" },
    { "target": "$run_id/net_out", "type": "timeserie" }
   ]
  },
  {
   "title": "Replication Lags",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/repl_lag", "type": "timeserie" }
   ]
  },
  {
   "title": "Query Executor",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 32, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/scan_objects", "type": "timeserie" },
    { "target": "$run_id/scan_keys", "type": "timeserie" },
    { "target": "$run_id/scan_sort", "type": "timeserie" }
   ]
  },
  {
   "title": "Ops In Progress",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 32, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/q_active_read", "type": "timeserie" },
    { "target": "$run_id/q_active_write", "type": "timeserie" }
   ]
  },
  {
   "title": "Network Physical Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 32, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/net_physical_in", "type": "timeserie" },
    { "target": "$run_id/net_physical_out", "type": "timeserie" }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Query Targeting (Scanned/Returned Ratio)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 38, "w": 8, "h": 6 },
   "targets": [
    { "target": "$run_id/query_targeting_keys", "type": "timeserie" },
    {
     "target": "$run_id/query_targeting_objects",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Document Metrics",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 38, "w": 8, "h": 6 },
   "targets": [
    { "target": "$run_id/doc_returned/s", "type": "timeserie" },
    { "target": "$run_id/doc_inserted/s", "type": "timeserie" },
    { "target": "$run_id/doc_updated/s", "type": "timeserie" },
    { "target": "$run_id/doc_deleted/s", "type": "timeserie" }
   ]
  },
  {
   "title": "Write Conflicts",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 38, "w": 8, "h": 6 },
   "targets": [
    { "target": "$run_id/write_conflicts/s", "type": "timeserie" }
   ]
  },
  { "title": "MongoDB 7.0+ Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Admission Control Queues",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 50, "w": 12, "h": 5 },
   "targets": [
    { "target": "$run_id/queues_read_out", "type": "timeserie" },
    { "target": "$run_id/queues_write_out", "type": "timeserie" },
    { "target": "$run_id/queues_read_available", "type": "timeserie" },
    { "target": "$run_id/queues_write_available", "type": "timeserie" }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 45, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/txn_active", "type": "timeserie" },
    { "target": "$run_id/txn_inactive", "type": "timeserie" },
    { "target": "$run_id/txn_open", "type": "timeserie" }
   ]
  },
  {
   "title": "Transaction Ops/s",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 45, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/txn_started/s", "type": "timeserie" },
    { "target": "$run_id/txn_committed/s", "type": "timeserie" },
    { "target": "$run_id/txn_aborted/s", "type": "timeserie" }
   ]
  },
  {
   "title": "Flow Control Rate Limit",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 55, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/flowctl_rate_limit", "type": "timeserie" }
   ]
  },
  {
   "title": "tcmalloc Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 50, "w": 12, "h": 5 },
   "targets": [
    { "target": "$run_id/tcmalloc_in_use", "type": "timeserie" },
    { "target": "$run_id/tcmalloc_allocated", "type": "timeserie" },
    { "target": "$run_id/tcmalloc_heap", "type": "timeserie" },
    { "target": "$run_id/tcmalloc_physical", "type": "timeserie" }
   ]
  },
  {
   "title": "Flow Control Time Acquiring (µs/s)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 55, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/flowctl_acquiring_us", "type": "timeserie" }
   ]
  },
  {
   "title": "Flow Control Lagged (/s)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 55, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/flowctl_lagged_count", "type": "timeserie" }
   ]
  },
  { "title": "System Metrics (CPU & Disks)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 61, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/cpu_system", "type": "timeserie" },
    { "target": "$run_id/cpu_user", "type": "timeserie" },
    { "target": "$run_id/cpu_iowait", "type": "timeserie" },
    { "target": "$run_id/cpu_idle", "type": "timeserie" },
    { "target": "$run_id/cpu_nice", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 61, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/disks_iops", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 61, "w": 8, "h": 5 },
   "targets": [
    { "target": "$run_id/disks_utils", "type": "timeserie" }
   ]
  },
  {
   "title": "I/O In Progress",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 66, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/disks_queue_length", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Total Wait Time",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 66, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/io_queued_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Read Wait Time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 66, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/read_time_ms", "type": "timeserie" }
   ]
  },
  {
   "title": "Disk Write Wait Time",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 66, "w": 6, "h": 5 },
   "targets": [
    { "target": "$run_id/write_time_ms", "type": "timeserie" }
   ]
  }
 ]
}