apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app.kubernetes.io/name: mongo-debugger
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
